### PR TITLE
Refactoring

### LINKED ISSUE #182: Cleanup TaskList View
We just merged the biggest [PR](https://github.com/200ok-ch/organice/pull/154 in) organice history.

✋ 🙌 🚀 🎉 and definitively 🎊  \(^_^)/

Amazing job, @schoettl 

Here's a list of consecutive todos based on that PR. None of them were close to being a blocker for merging, of course:

- [x] Document 
  - TaskList with search
  - UX change: Plus for capture
  - Routing for Settings and Sample
  - Routing for Agenda and TaskList
- [ ] Go through [the last code review](https://github.com/200ok-ch/organice/pull/154) from Jakob
- [ ] Move the [discussion](https://github.com/200ok-ch/organice/pull/154#issuecomment-569548209) with alphapapa into an issue
- [ ] Debounce search input (on big files it can be quite slow otherwise)
- [ ] Fix bug: on iOS (scrolling a long doesn't TaskList does not work)
- [ ] Discuss strategy on Search and TaskLists
- [ ] Write documentation in `sample.org`
  - Maybe take docs from https://github.com/200ok-ch/organice/issues/141
- [ ] Refactor TastListView and TaskListModal 
  - [ ] Make them Functional Components
  - [ ] Move `TaskListView.getPlanningItemsAndHeaders()` out of the `render` cycle
  - [ ] Refactor Leftover Agenda Markup
- [ ] Refactor `OrgFile.extractAllOrgTags` out of the component
  - This can be done more efficiently in the Reducer

### PR DESCRIPTION
**Pull request by schoettl**
This should close #182: Refactor and clean-up after the search filter PR.

- [ ] On invalid filter syntax, all items are displayed. Instead, the current view should not be changed.
- [ ] Having unpushed changes, the browser pops up an dialog, asking to continue (see comment below). Create GIF and separate issue if not easily resolvable.
- [x] Add documentation for filter/search feature to sample.org.

...

### CODE REVIEW

**Comment by schoettl** [comment]
Refactoring, starting with this:

I recently read docs on Immutable.js. It says:
Map() and List() are not classes but factory functions

https://immutable-js.github.io/immutable-js/docs/#/List/List

I used this regex
```
new +(Map|List)\(\)
new +(Map|List|Set|OrderedMap|Stack|OrderedSet)\(\)
```
the latter does not find any more.

**Comment by schoettl** [comment]
@munen after you refactored the modals to have their own URLs, my chrome browser on Android always asks me when I open a modal:

> You have unpushed changes - are you sure you want to leave this page?

Can we only show this dialog when the page is really about to be left, not for modals?

I also noticed, that now the agenda modal does not have this horizontal bar at the top (all other modals have it). Was that by purpose?

**Comment by munen** [comment]
@schoettl Android and iOS browsers...

We are not showing dialogue on purpose. There are also never changes in an Agenda or TaskList Drawer that need persisting. So it’s a made up problem by the browser-_-

Can you debug this further? I have no access to an Android phone. 

> I also noticed, that now the agenda modal does not have this horizontal bar at the top (all other modals have it). Was that by purpose?

Which horizontal bar?

**Comment by schoettl** [comment]
> Which horizontal bar?

The em-dash like bar on the top that indicates that the modal can be drawed away on this handle :)

**Comment by schoettl** [comment]
> We are not showing dialogue on purpose. There are also never changes in an Agenda or TaskList Drawer that need persisting. So it’s a made up problem by the browser-_-
> 
> Can you debug this further? I have no access to an Android phone.

I mean, the browser message is a custom message, it must be somewhere in the source and maybe triggered on an event. I'll set it on the list.

**Comment by munen** [comment]
> The em-dash like bar on the top that indicates that the modal can be drawed away on this handle :)

Then the design just doesn’t work the same on Android as it does on the desktop. The handle is there. I think I’ve set the height of the drawer to 94% or similar, for Android (or just your device/Android version) it needs to be smaller. 

Can you experiment with this?

No worries, btw. I’m not only bashing Android. There’s iOS render bugs on the new feature as well that. Scrolling doesn’t work and if there’s overflowing content, it overlaps with the checkbox. 

Those are the fun UI Bugs - when it’s not responsive design, because it works in the same resolution on the browser, but a specific iOS/Android bug.

**Comment by munen** [comment]
> I mean, the browser message is a custom message, it must be somewhere in the source and maybe triggered on an event. I'll set it on the list.

If possible, make a gif showing how to reproduce it. It improved the chances Someone can help.

**Comment by schoettl** [comment]
@munen Noted to TODOs.

I cannot see my changes in sample.org yet in the app... is that normal?

**Comment by munen** [comment]
@schoettl The file is read on startup atm. You’ll see the changes after a restart of `yarn start`.

**Comment by munen** [comment]
I just read the diff - great doc!

When you reload the server, you’ll unfortunately see a restriction of the renderer when you look at it in responsive mode. The newlines are true newlines atm. Hence, the text will have intermittent newlines. 

Better would be to treat newlines whilst in responsive mode like a reverse `format flowed` from MUAs.

For the time being, I suggest to put a paragraph in one line. I’m not saying that this is my true personal preference, though^^

Anyway, super docs for an amazing feature!

**Comment by schoettl** [comment]
Thanks for the feedback. No problem, I change it, I just didn't know how it will render. Also, organice does not yet know the orgmode colon syntax for code. I'll write it a different way.

**Comment by munen** [comment]
> Also, organice does not yet know the orgmode colon syntax for code. I'll write it a different way.

You're right, it doesn't support the colon syntax.

To nitpick, it's not 'syntax for code', it's a 'literal example'(; https://orgmode.org/manual/Literal-examples.html

I use them a lot when setting named variables in documents that need some programming to produce prose (like a Controlling document). So I wouldn't mind if organice rendered those correctly(;

**Comment by munen** [comment]
The changes look great to me. 

I made some markup adjustments and made sure those are rendered correctly in organice.

I'm pulling the changes in so that everyone can have the benefits as soon as possibe. I'll move the open tasks from the  PR description back to the original issue.

**Pull request merged**
