### PR TITLE
Replace some <a> tags with <ExternalLink>

### PR DESCRIPTION
**Pull request by schoettl**
The first examples looked like this interface is good: `<ExternalLink href="url" content="text" />`

But later, I stumpled upon links with HTML tags inside, so it's probably better to allow children as described here: https://reactjs.org/docs/composition-vs-inheritance.html

Any reason to keep the `content` property and only use its value instead of childen if no children? Maybe it's a little bit shorter? But I think it's cleaner to have only one "interface".

### CODE REVIEW

**Comment by munen** [comment]
> Any reason to keep the content property and only use its value instead of childen if no children? Maybe it's a little bit shorter? But I think it's cleaner to have only one "interface".

I'd prefer to have only the children interface. It feels more like a 'normal' HTML tag.

**Review by munen — CHANGES_REQUESTED** [review]
> Any reason to keep the content property and only use its value instead of childen if no children? Maybe it's a little bit shorter? But I think it's cleaner to have only one "interface".

I'd prefer to have only the children interface. It feels more like a 'normal' HTML tag.

That is, if it is OK for you. Otherwise, I don't mind to have the `content` property, as well. Would be less refactoring, so that's an upside^^

**Comment by schoettl** [comment]
OK, ready for review and merge.

**Comment by munen** [comment]
@schoettl Code looks good and manual tests also worked fine on the links.

Before merging, I wanted to run `yarn test` locally once and saw this:

image

It's reproducible and I don't have it on `master`. Unfortunately, I also have no first hunch on what the error entails.

**Comment by schoettl** [comment]
Thanks, I didn't see this warning in the first run. `key` is a reserved property, I didn't knew that.

@munen Before we merge, I'd like to fix a dead link on the landing page (when not signed in). Where is the Documentation button intended to link to? Currently it is `/documentation.html` which doesn't exist and is also not a nice URL ;)

**Comment by schoettl** [comment]
Ah, got it. It must be the full URL because the link would be dead if organice is hosted elsewhere.

**Comment by munen** [comment]
@schoettl Looks and works great, happy to merge. Thank you for the additional changes! :pray: 

Also good to know that `key` is a reserved keyword! :smile:

**Pull request merged**
