### PR TITLE
"Share" button for headlines

### PR DESCRIPTION
**Pull request by schoettl**
#142 

Currently only simple e-mail sharing (not yet tested on smart phones).

### CODE REVIEW

**Comment by schoettl** [comment]
I think this branch is ready for testing.

It is plain sharing via e-mail.

However, for opening the mail client with a `mailto:` link, there is not one way to do it. And browser may behave different and change their behavior. I used the `window.location.href = 'mailto:...'` solution.[1] It works in current Firefox and Chromium on Arch.

How can I test in on the phone? The last time I tried it, I couldn't connect to Dropbox, I think because during auth, the phone provided no domain name, but only the IP of my computer to Dropbox OAuth...

If it's OK, I would like to merge this branch and implement more complex support for OS share systems later.

[1] https://stackoverflow.com/q/21461589/999007

**Comment by munen** [comment]
@schoettl 

> How can I test in on the phone? 

The easy way (when you don't actually need synchronization): Just open the sample.org file. That works without logging in.

The harder ways: 

1. The Dropbox app for organice.200ok.ch is configured to accept connections from localhost:3000 - so you can use it easily from your Desktop. And you can use it from your phone as well, if you do a port forward to make the phones localhost:3000 point to your organice server on the Desktop.
2. Use ipv6 and set up a custom domain for your machine. Configure your own Dropbox app for this domain. Note: You'll have to use HTTPS for that.

I'm usually doing the easy version or the port forward. The last option would be nice to set up once and then keep it. The best option for that would be to add a Docker container for nginx with letsencrypt that acts as a proxy for organice. There's two containers already set up to do something like this:
- jwilder/nginx-proxy
- jrcs/letsencrypt-nginx-proxy-companion

**Comment by munen** [comment]
NB: I did test on iOS. The current implementation works in mobile safari and as a PWA!

**Comment by schoettl** [comment]
@munen Thank you for the explanation (we could add it to a wiki or doc).

> 1. The Dropbox app for organice.200ok.ch is configured to accept connections from localhost:3000 - so you can use it easily from your Desktop. And you can use it from your phone as well, if you do a port forward to make the phones localhost:3000 point to your organice server on the Desktop.

But I don't quite understand this part. Do you mean like adding a row to my (Android) phones' `/etc/hosts` file? I guess it's only possible on a rooted phone, right? Or are they dev options on the phone for this?

**Comment by munen** [comment]
@schoettl I made minor changes, tested on iOS (browser and PWA) and added an integration test. If my small changes are OK for you, please remove the WIP from the title. I'll happily merge your PR in, then!

There's one slightly bigger thing I did: I changed the call from window.location.href to window.open. This leads to a slightly worse UX (popup), but I was able to test it. Mocking the `window` object turns out to be quite hard. What do you think about that? Having slightly worse UX in favor of having a test is not optimal, as well, of course.

In any case: Thank you for the great work. As always, it's a very nice improvement!

**Comment by munen** [comment]
> Thanks for this fixes! I left the three lines of comments to make it easier when we want to share more information in future.

Sure thing. I was assuming so and that's why I left them in(;

**Comment by schoettl** [comment]
I tested on Android (and as mentioned above in Firefox and Chromium).

I guess I found a bug in the Gmail app on Android. If there is a `%` (e.g. an org "cookie") in the header, it produces an undefined character in the Gmail mail subject.

But as it is URI-encoded correctly and works on Linux/Thunderbird, I guess it's not our fault.

**Comment by munen** [comment]
> Thank you for the explanation (we could add it to a wiki or doc).

Sure, we could add it to the README in the dev section. Would you want to write a first draft for that?

> But I don't quite understand this part. Do you mean like adding a row to my (Android) phones' /etc/hosts file? I guess it's only possible on a rooted phone, right? Or are they dev options on the phone for this?

Changing the /etc/hosts file to point to a different machine for localhost would probably screw up some things. In any case it would require rooting your phone.

No, I meant port forwarding as in SSH port forwarding (documented in `man ssh` under the `-L` flag, or in articles like this one: https://help.ubuntu.com/community/SSH/OpenSSH/PortForwarding)

Since I don't have a rooted phone (iOS), I'm using a dedicated ssh application (https://www.termius.com/) for that. If you have a shell on your phone (which is more likely since you are an Android user^^, you could just use ssh like this: `$ ssh -L 3000:localhost:3000 you@your-dev-machine`

**Comment by munen** [comment]
I'm fine with not supporting edge cases of GMail(;

**Comment by munen** [comment]
My wife keeps calling. Will come back tomorrow to this thread.

Let me know if you're happy with the change regarding window.open and if I should merge.

**Comment by schoettl** [comment]
> There's one slightly bigger thing I did: I changed the call from window.location.href to window.open. This leads to a slightly worse UX (popup), but I was able to test it. Mocking the `window` object turns out to be quite hard. What do you think about that? Having slightly worse UX in favor of having a test is not optimal, as well, of course.

That might actually be a good change in that it makes it working "safer". Because sometimes Chromium asked me, if I really want to "change window.location.href" because there might be changes that will be lost or so...
That should not occur with `window.open()`.

I will remove the [WIP] to mark it ready for merge. Before that, I quickly want to add a comment on this decision in the code.

**Comment by schoettl** [comment]
Ah, you already did comment on this decision, great :)

**Comment by munen** [comment]
I also have a hunch that calling to the object will be deprecated in the future. It’s a little weird that setting an attribute on an object has this kind of side effect. I guess that’s why `window.open` is there.

**Comment by munen** [comment]
Very well, let's get this merged, then!^^

**Comment by munen** [comment]
I've added it to the changelog and added your attribution: https://github.com/200ok-ch/organice/commit/b7c548d3a589fbb67e1ae1c403cd5086f3627c10

Thank you for this great feature addition, @schoettl! :pray:

**Pull request merged**
