### PR TITLE
Teach #+TODO parser to understand (..) suffix (#184)

### LINKED ISSUE #184: #+TODO doesn't understand (x) suffixes for keyboard shortcuts
[This was originally reported in #151, but is now split out into this issue.]

I need to keep my `TODO.org` synchronised between my desktop/laptop/mobile phone/tablet, with the intention of using emacs on desktop/laptop, and organice on mobile phone/tablet.

I have a fairly complex configuration for my `TODO` keywords.  I have `org-todo-keywords` customised to:

```elisp
((sequence "NEXT(n)" "STARTED(>)" "|" "DONE(d)")
 (sequence "PROJECT(p)" "PROJDONE(P)")
 (sequence "ONGOING(o)" "WAITING(w@)" "CHASE(C@)" "|")
 (sequence "SOMEDAY(s)" "MAYBE(m)" "|" "CANCELLED(c)"))
```

Since organice does not know about elisp configuration, I added this to near the bottom of my `TODO.org`:

```org
* org-mode settings
*** TODO keywords
#+TODO: NEXT(n) STARTED(>) | DONE(d)
#+TODO: PROJECT(p) PROJDONE(P)
#+TODO: ONGOING(o) WAITING(w@) CHASE(C@) |
#+TODO: SOMEDAY(s) MAYBE(m) | CANCELLED(c)
```

Note that [the letters in parentheses define keyboard shortcuts providing fast access to TODO states](https://orgmode.org/manual/Fast-access-to-TODO-states.html#Fast-access-to-TODO-states), so that within emacs I can hit (say) `C-c C-t p` to immediately change a headline to `PROJECT`.

However organice does not understand these parenthetical suffixes.  All the above keywords are treated like normal headline text, i.e. it thinks I want three keywords called `NEXT(n)`, `STARTED(>)`, and `DONE(d)`.  So if I have a line like this in organice:

    *** NEXT some task

and I swipe right, I'll get:

    *** NEXT(n) NEXT some task

because it's treating `NEXT` as if it's part of the headline.  Obviously this is completely wrong and I actually want the three keywords to be `NEXT`, `STARTED`, and `DONE`.

So the immediate goal is simply to change organice's parser to ignore the suffixes in parentheses.  That should be really easy.  Of course we'll also want some unit tests to ensure we avoid any regressions when switching to `org-parser` later on.

Even later on, we could potentially add some kind of support for keyboard shortcuts which honour these suffixes within organice, but for me personally that is extremely low priority as I would probably never use it, since I'm very unlikely to use organice on a desktop / laptop, and only want to use it my phone or tablet.  However I still need to keep those suffixes on the `#+TODO` line because as mentioned above, I rely on them when using emacs on desktop / laptop, and I need to keep the same file synchronised between my computers and mobile devices.

**Desktop (please complete the following information):**
 - OS: openSUSE Linux
 - Browser: Chrome 79

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - OS: Android 9.0.x
 - Browser: Brave and Chrome

### PR DESCRIPTION
**Pull request by aspiers**
The in-buffer settings supported by both Org and organice include modifying the TODO keywords, e.g.

    #+TODO: START INPROGRESS STALLED | FINISHED

or

    #+TYP_TODO: START INPROGRESS STALLED | FINISHED

Org supports adding a suffix in parentheses to any of these keywords in order to configure fast-access keyboard shortcuts:

- https://orgmode.org/manual/Fast-access-to-TODO-states.html#Fast-access-to-TODO-states

or to track TODO state changes:

- https://orgmode.org/manual/Tracking-TODO-state-changes.html#Tracking-TODO-state-changes

For example:

    #+TODO: START(s) INPROGRESS(i!) STALLED(.@/!) | FINISHED(f@)

However, organice gets hopelessly confused by files which use this syntax as described in #184.  So make the parser smarter, initially simply by ignoring these suffixes so that organice will not change behaviour, in a way which allows taking advantage of them later on.

Fixes #184.

### CODE REVIEW

**Comment by munen** [comment]
@aspiers Perfect execution! I like how you documented everything nicely with tests and removed some complexity by extracting a function out of the super long `parseOrg` function.

NB: I added one more inline comment in the parser and moved the other parser unit tests from Orgfile unit tests to your new which is the correct place for these kinds of tests.

I'll happily pull in your changes \(^_^)/

Great job! :pray: :bowing_man:

**Comment by munen** [comment]
@aspiers I have updated the changelog with your attribution: https://github.com/200ok-ch/organice/commit/65adc621ec3581620623b7efbc59ba1b4451ff00

Thanks, again :pray:

**Comment by munen** [comment]
PS: There was one error in the PR that I also missed before merging. I fixed it here: https://github.com/200ok-ch/organice/commit/8474ae290dc17b75fcb31177a92b1be95058a4b7

This warning was shown when run `yarn start`:

```
./src/lib/parse_org.js
  Line 736:3:  Unreachable code  no-unreachable
```

When building the applications, eslint warnings are treated as errors. I wanted to add eslint to the CI run for a longer time (https://github.com/200ok-ch/organice/issues/64), but it's not trivial due to the project having been bootstrapped with create-react-app.

**Comment by aspiers** [comment]
[**@munen**](https://github.com/munen) commented on [January 2, 2020 10:34 PM](https://github.com/200ok-ch/organice/pull/202#issuecomment-570380382 "2020-01-02T22:34:35Z - Replied by Github Reply Comments"):
> PS: There was one error in the PR that I also missed before merging. I fixed it here: [8474ae2](https://github.com/200ok-ch/organice/commit/8474ae290dc17b75fcb31177a92b1be95058a4b7)
> 
> This warning was shown when run `yarn start`:
> 
> ```
> ./src/lib/parse_org.js
>   Line 736:3:  Unreachable code  no-unreachable
> ```

Oops, sorry about that :-(

> When building the applications, eslint warnings are treated as errors. I wanted to add eslint to the CI run for a longer time ([#64](https://github.com/200ok-ch/organice/issues/64)), but it's not trivial due to the project having been bootstrapped with create-react-app.

Maybe worth explaining in #64 what the challenge is, in case someone feels inclined to fix it?

**Comment by munen** [comment]
> Oops, sorry about that :-(

No worries, it happens sometimes. That's what the linter is for^^

> Maybe worth explaining in #64 what the challenge is, in case 
> someone feels inclined to fix it?

Good point. I'll do that!

**Pull request merged**
