### PR TITLE
Update link in README.org

### PR DESCRIPTION
**Pull request by chrisbodhi**
Update link to jump to section on PWA

### CODE REVIEW

**Comment by chrisbodhi** [comment]
Failing test says

```
Loading /etc/emacs/site-start.d/00debian.el (source)...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Contacting host: raw.githubusercontent.com:443
Loading tramp-gvfs...
Unable to resolve link: "progressive-web-app--offline-support"
Error: failed to build documentation

Exited with code exit status 1
```

I tested the change on my branch, and it worked as expected. I'm unsure how to proceed.

**Comment by munen** [comment]
Hi @chrisbodhi 

Thank you for contributing to organice :pray: 

I can tell you why CI is complaining. You've changed a link, but did not update the target. So the link is broken. Good catch on CI, I'd say(;

https://screenshots.200ok.ch/screenshot_2021_01_09-f3a80c7a.png

NB: I'm not quite sure what you want to achieve with this change, though. The link is already quite semantic. Changing it risks creating dead links.

Thanks for looking into contributing!

**Comment by chrisbodhi** [comment]
Ah, thank you for explaining, @munen. And apologies for being unclear about my reasoning for making the change -- the link wasn't working in GitHub's interface. But, I see now that the link is working as expected when using the org file in org-mode. :D 

It seems that the discrepancy in functionality has to do with how GitHub renders org files, so I'll close the PR. Thanks again!

**Comment by munen** [comment]
@chrisbodhi Unfortunately, GH doesn’t render all Org links correctly. However, the official organice docs are more extensive than just the readme. And the links work, too(;

Here are the docs: https://organice.200ok.ch/documentation.html

**Pull request closed without merging**
