### PR TITLE
Update Android/Firefox instructions in README

### PR DESCRIPTION
**Pull request by pakelley**
Looks like Firefox has changed how to do this. I'm on the most recent version of Firefox (on a Pixel, fwiw), but can't vouch that this is the process for most Firefox versions (or android devices) in use, so I'm happy to "append" this rather than editing the old version, if you'd prefer.

### CODE REVIEW

**Comment by munen** [comment]
Hi @pakelley

Thank you for taking the time to update the docs, it is much appreciated! Can you rewrite the docs to state that if the one UX does not work, then the other might? This might be prudent considering that there's usually a few users with older phones and operating systems, in any case.

Thank you, again, for your support! :pray:

**Comment by pakelley** [comment]
Alright, both are included now. Lmk if the wording looks alright to you, I don't mind doing another pass if you want something changed. :)

**Comment by munen** [comment]
Hi @pakelley 

Thank you for the quick update! I'm happy to merge it in.

Thank you, again, for the effort and helping us to keep the docs up to date🙏

**Comment by pakelley** [comment]
no problem, thanks for your work on organice 🙂

**Pull request merged**
