### PR TITLE
breadcrumbs for search

### PR DESCRIPTION
**Pull request by tarnung**
#213
At the moment the breadcrumbs always include the filename as a first element.

### CODE REVIEW

**Comment by munen** [comment]
I like this very much. It's exactly what I had in mind. Thank you for taking a stab at it!

I would have taken some time to fix the tests, but first I wanted to fix the issue that this does not work for the `sample` file. The sample file currently is in a weird state - it's not a regular file, it's static, and triggered via an action as a modal. Then, `path` will be `null`.

Therefore, search will crash on the `sample` page at the moment. I tried fixing it with:

image

But that yields a new problem: Now, the search file is a 'proper' file and wants synchronization to happen(;

I think my approach to the fix is ok-ish, but needs more work.

---

Related to the last statement and my lack in swift responses to your last amazing PRs, I want to give you some feedback. For the last two years, I've been building a product with Phil which is a huge investment. Tomorrow, at 11pm it will go live with our first huge enterprise customer. Hence, I'm working rather long days at the moment and couldn't get to your PRs before. But, I've seen them and am super stoked about each and every one of them!

I have a good feeling that going live with the product will go over rather smoothely. That will free up some time in the near future.

Also, it will pay nicely for our FOSS endeavours(;

Just wanted to let you know what I've been up to and why I wasn't as responsive as I would have been in other circumstances.

Great work and huge effort on your part! :pray: :bow:

**Comment by tarnung** [comment]
> Related to the last statement and my lack in swift responses

No worries. Even though you committed to some kind of response by declaring organice a community project, I don't expect you to be beholden to any kind of SLA ;) I'm very happy with your detailed feedback. I won't always have this much time to invest into this project, but for now I enjoy seeing where I can take this. Thank you for setting up the project in a way that facilitates this.

**Comment by tarnung** [comment]
Changelog explodes too. I guess it's in the same kind-of-but-not-quite-a-file limbo as sample.

**Comment by munen** [comment]
> No worries. Even though you committed to some kind of response by declaring organice a community project, I don't expect you to be beholden to any kind of SLA ;)

*hihi*, thanks(;

I would argue that it is a community project, already. I'm but one of 6 people with write access and only one other from those six is from the 200ok.

I do appreciate, though, that everyone seems to be inclined to let me get a word in regarding how organice evolves🙏

> I'm very happy with your detailed feedback. I won't always have this much time to invest into this project, but for now I enjoy seeing where I can take this. Thank you for setting up the project in a way that facilitates this.

You're very welcome - apart from organice being really useful in day to day life and business, it's a really fun project where working together with quite a few people is not only possible, but a potentially quite nice experience for everyone involved. Thank you for being part of that journey!

> Best of luck for the Go Live!

Thank you, it's been another full week, but the go-live was a big success, too. Nearly all 2000 daily articles and images on bluewin.ch are coming from us, now. Soon (in a week or so), videos will be from us, too.

> Changelog explodes too. I guess it's in the same kind-of-but-not-quite-a-file limbo as sample.

Yes, that's right. organice bundles changelog and sample as static files right when initially starting the application: https://github.com/200ok-ch/organice/blob/b3c26761f83dc8d23143eead78526980643be7b5/src/actions/base.js#L37-L38

**Comment by tarnung** [comment]
> the go-live was a big success 
🎉 Phil showed me this project in an early state a long time ago. Nice to hear that you could launch it sucessfully!

Is it possible to have this and the file settings pr merged into develop? Then I could continue on the current combined state.

**Comment by munen** [comment]
> :tada:  Phil showed me this project in an early state a long time ago. Nice to hear that you could launch it sucessfully!

:pray: 

> Is it possible to have this and the file settings pr merged into develop? Then I could continue on the current combined state.

Sure, I'll merge https://github.com/200ok-ch/organice/pull/560 and https://github.com/200ok-ch/organice/pull/565  to `develop` right now!

I did add some comments to https://github.com/200ok-ch/organice/pull/565

**Pull request merged**
