### PR TITLE
Parse and render URLs, mail-addresses and phone numbers

### PR DESCRIPTION
**Pull request by schoettl**
Issue #23

### CODE REVIEW

**Comment by schoettl** [comment]
It does not work yet: it seems like the additional regex parts (URL, e-mail, phone number) are not parsed although the regex work at https://www.debuggex.com/

@munen and I don't know how to run the *.unit.test.js files.

**Comment by munen** [comment]
@schoettl You can run the tests with `yarn test`.

**Comment by schoettl** [comment]
Ah, thanks, that work.
`yarn -h | grep test` did not mention that the test command exists :)

**Comment by munen** [comment]
Nice that you tried to find how to run the tests!(;

It's not a standard flag for `yarn` as `yarn` is a generic dependency management tool.

However, `yarn` uses the same `package.json` file that `npm` introduced. Within it, it is best practice to have a 'scripts' hash declaring how to `start` and `test` the application.

NB: For future contributors, I added how to run tests in the ["development" section of the README](https://github.com/200ok-ch/organice#development).

P.S.: I like you already wrote tests despite you didn't know yet how to run them 👍

**Comment by munen** [comment]
Generally speaking, if you want to know what other scripts `yarn` or `npm` have to offer, you can either look it up in the `package.json` file, or you can run `yarn run` which gives you a list and potential description.

**Comment by schoettl** [comment]
Ah, I see the "scripts" key in the package.json. Thank you for the explanation!

**Comment by munen** [comment]
Quickly looking over your PR, I have a small request: I know that the `markupAndCookieRegex` variable is not your mess. However, before we merge this PR, I'd like to invoke the [boy scout rule](https://deviq.com/boy-scout-rule/) in that it would be nice if we wouldn't make this super long and unreadable regexp any longer, but instead implement the new logic as a composable regex. I'm not saying we have to also clean up the old expressions, but implementing the new logic in a composable manner would leave the code a little cleaner and easier to test. Would that be ok for you? Not that you have to do it straight away, of course. Making it first work and then making it better totally works, of course!

**Comment by munen** [comment]
> Ah, I see the "scripts" key in the package.json. Thank you for the explanation!

You're welcome, any time 🙏 

The whole React front-end ecosystem is quite complex and you said that it's new for you. For that, you're groking the whole codebase super fast! 🚀 :godmode:

**Comment by schoettl** [comment]
Yes, you're right. I will have to look into the parser details to find out, how we can refactor it.

**Comment by munen** [comment]
Great, big thanks!^^

**Comment by schoettl** [comment]
@munen I think this is pretty ready for merge. I opened issue #150 for refactoring but I rather would to do that in a separate PR.

Could you review, comment, test a bit?

It even works in properties, e.g.

```
* Test

:PROPERTIES:
:assignee: Jakob Schöttl <my@email.org>
:END:

+Don't+ call me on: +498025123456789 (should become a tel: link)

An URL https://foo.bar.baz/xyz?a=b&d#foo and /more text/ and
this is an e-mail foo.bar@baz.org in a line of text.
```

Of course there is still room for enhancements like
- shorten long URLs with ellipses ... (only the displayed URL)
- support www.example.com URLs without protocoll
- support ftp: or other protocols

**Comment by munen** [comment]
@schoettl Great job! This is just about good to be merged.

I have added user acceptance tests to your branch in this commit: https://github.com/200ok-ch/organice/pull/147/commits/d2f369ff514a21a15361ff9702fdec2f025e8595

When you run them, make sure to run `yarn install` before.

The tests you wrote are good. They ensure that the parser and the exporter will not change the original Org file by one byte. To prove that the user also sees the behavior as described by you, I added the acceptance tests.

While doing so, I did catch one error. Interestingly, I caught it only because I used the same line for the URL recognition test that you used in the unit test. The test would run if there wouldn't be a `=URL=` in the line. Here's a screenshot showing the issue:

image

This is the header I used for manual testing:

```
* TODO Header with different kinds of links
  
This is a test https://200ok.ch

http://200ok.ch

200ok.ch

Call me on +41764050567.

Write me to alain@200ok.ch.

an URL https://foo.bar.baz/xyz?a=b&d#foo and /more text/ and so 


an =URL= https://foo.bar.baz/xyz?a=b&d#foo and /more text/ and so 

Just a regular =URL= in some text.

This is an e-mail foo.bar@baz.org in a line of text. 

+Don't+ call me on: +498025123456789 (should become a tel: link) 
```

It's not a major issue, but if you could fix it before we merge it in, that would be nice. If you can't find it, I'll have a look. If I won't find it, let's change the test to not use `=URL=` in the line and then it'll run.

In any case, you're about to have contributed yet another great feature to organice! :pray: :bowing_man:

**Pull request merged**
