### PR TITLE
feat: suggestion for clock:now

### PR DESCRIPTION
**Pull request by tarnung**
A quick and dirty implementation for parts of the feature set described in #737

=> clock:now searches for active clocks

I thought that other things than clocks can create "logBookEntries". But maybe i misremember. I could not find any in my demo files.

This pull request does not address the issue #745. Since it does not add to the problem we can go along and refactor later once @schoettl and I what if anything should be done.

### CODE REVIEW

**Comment by tarnung** [comment]
I added a basic indicator for active clocks. It checks for them when parsing the org file and updates their number when clocking in/out.
It currently just turns a button red. This should probably be surplanted by a solution that is more theme aware.

**Comment by tarnung** [comment]
The indicator can get out of sync when headers with active clocks are deleted. Maybe there's a more robust implementation, maybe this is good enough as it corrects itself on the next file parse.

**Comment by munen** [comment]
Nice PR!

> I thought that other things than clocks can create "logBookEntries". But maybe i misremember. I could not find any in my demo files.

A `:LOGBOOK:` drawer can also contain a state change for a task. For example updating this task:

```
* TODO Repeating task
  SCHEDULED: <2019-11-27 Wed +1d>
````

will become:

```
* TODO Repeating task
  SCHEDULED: <2019-11-28 Thu +1d>
  :PROPERTIES:
  :LAST_REPEAT: [2021-11-09 Tue 14:39]
  :END:
  :LOGBOOK:
  - State "DONE"       from "TODO"       [2021-11-09 Tue 14:39]
  :END:
``` 

Example taken from https://github.com/200ok-ch/organice/blob/master/test_helpers/fixtures/various_todos.org#repeating-task

Relevant Org mode doc: https://orgmode.org/manual/Drawers.html

Having said that, your `hasActiveClock` implementation looks solid enough that it will only trigger on actual clocks(;

**Comment by munen** [comment]
I have gone through the code and tested it. It works for me and I like the implementation.

I haven't merged, yet, for this reason: Since the magnifying glass already changes color, I'd say this PR also needs the icon that populates a search with `clock:now`. Otherwise the magnifying glass indicates something that is actionable, but the user doesn't know what. Alternatively, to get this PR quicker into `master`, we can remove the color change and add it at a later date.

**Comment by tarnung** [comment]
this pr is replaced by #751 if the changes over there are accepted

**Comment by chasecaleb** [comment]
Nice job on this, thanks for implementing @tarnung!

**Pull request merged**
