### PR TITLE
fix: use input type url instead of text for gitlab url

### PR DESCRIPTION
**Pull request by branch14**
Input type text on Android will automatically insert a space after each dot. This is unwanted behavior when entering a URL. Input type url will AFAIK not yield any other benefits nor side effects apart from not inserting the space after the dot.

### CODE REVIEW

**Comment by munen** [comment]
Lgtm :pray: 

Let's merge to develop and test on iOS and Android.

**Comment by schoettl** [comment]
The webdav sign-in also has this input type url. But I think type url requires the protocol (https://) which was not required before... don't know how the webdav backend handles this value.

**Comment by schoettl** [comment]
... so now, if I try to input an URL without protocol (like the placeholder text says), I got an browser error hint when trying to submit ("Sign-in").

**Comment by schoettl** [comment]
I think type url is OK. I tested on Firefox (Desktop). But 1. and 2. should be fixed.

**Pull request merged**
