### PR TITLE
Bugfix for timestamp parsing

### PR DESCRIPTION
**Pull request by schoettl**
I found a bug in the timestamp parsing: the day part was defined as `[^0-9]+`. This includes `>` and whitespace (including newlines).

The test in my first commit fails with:
```
    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

    - Tue
    + Tue>
    + - [ 
```

Since I cannot find a spec for orgmode timestamps, I just fix it with `[^0-9\s]`.

### CODE REVIEW

**Comment by munen** [comment]
@schoettl Hell, yeah!

FYI, you just fixed PR https://github.com/200ok-ch/organice/pull/48 and related issue https://github.com/200ok-ch/organice/issues/47

Great catch and even greater PR. Happily pulling it in right away! :pray: :bowing_man:

**Comment by munen** [comment]
I have updated the changelog with attribution: https://github.com/200ok-ch/organice/commit/2116e00df0f2ac979eda9146c3389143341a89c3

**Comment by schoettl** [comment]
Good that you remembered the related issues!

**Comment by munen** [comment]
Every now and then I would run into the bug again and would see it in the diffs. Great that nobody has to see that anymore :tada:

**Comment by schoettl** [comment]
> Since I cannot find a spec for orgmode timestamps, I just fix it with `[^0-9\s]`.

PS: There is no character class for "all letters" in JS and `[a-zA-Z]` might not work for day names in other languages (if that is allowed), that is why I did not fix it with `[a-zA-Z]`

**Comment by munen** [comment]
Org uses ISO 8601 (source https://orgmode.org/manual/Custom-time-format.html).

Hence, it can have localized day names (here's the [PR](https://github.com/DanielDe/org-web/issues/69) that added it to org web).

**Pull request merged**
