### PR TITLE
feat(ux): Ticking a checkbox as part of a list item

### PR DESCRIPTION
**Pull request by munen**
As discussed in https://github.com/200ok-ch/organice/discussions/950

@neildavidforrest and @kjmatsuda: Can you please test this PR and see if it is to both of your liking?

foo

### CODE REVIEW

**Comment by kjmatsuda** [comment]
Hi @munen , I tested this feature! I like behavior of this PR👍

**Comment by munen** [comment]
@kjmatsuda Sweet, thank you for testing! 🙏🏻

I’ll wait for confirmation of @neildavidforrest that this PR is an accurate implementation of his compromise proposal before merging.

**Review by neildavidforrest — APPROVED** [review]
Hi @munen, that was fast! Tested here too on desktop and mobile, works great. Thanks.

**Comment by munen** [comment]
Thank you both for the swift tests and positive feedback, @kjmatsuda and @neildavidforrest 🙏🏻🙇‍♂️

I’ll pull the changes in, then.

**Pull request merged**
