### PR TITLE
Search and Task List in one Modal

### PR DESCRIPTION
**Pull request by tarnung**
This PR sits on top of #748 and #747 and adresses task one in #211.

- Search and Task List open in one modal with tabs
- modal opens to "Search" by default and remembers what was opened last (not persisted to backend)
- **NO LONGER TRUE:** if there are open clocks, the last opened modal is ignored and it always opens to "Search" for "clock:now".
- **instead:** if there are open clocks, a third modal "Clock List" is added that looks like "Search" for "clock:now" without the search input field.

Feel free to discuss if this is a sensible behaviour. 

A caveats:
This is a design refactor. It still uses SearchModal and TaskListModal under the hood so there was no cleaning up of duplicated functionality.

### CODE REVIEW

**Comment by tarnung** [comment]
I pushed to develop.

**Comment by tarnung** [comment]
It's deployed to develop.

**Comment by munen** [comment]
Thanks for deploying!🙏🏻

Sitting in a train from TI to GL and starting to test on my phone. First impressions: 🚀🎉🤩

**Comment by tarnung** [comment]
I've deployed another minimal style change that fixes the annoying detail that the height of the search bar changed based on the amount of headers found by the search.

**Comment by tarnung** [comment]
In #217 there was a discussion about the "set deadline" and "set scheduled" buttons immediately creating timestamps.

An argument in favour was that you otherwise would need more clicks to create the timestamp. I don't fully share that concern as you probably don't want to set a scheduled event or a deadline to "now" so you will need several more clicks to configure the timestamp anyways.

In addition if I use the new in modal buttons to switch between editing different parts of the header i have another chance to accidentally create timestamps. If I delete the timestamp I get thrown out of the modal - which none of the other header focussed modals that you can switch between does on deletion of say a tag or a property.

If there are strong opinions against that, it's easy to change it back since it's one commit.

Quick aside:
Timestamps are annoying to delete on my android: 
- I need to press the date to open the datepicker
- The bottom part of the datepicker says "pick" and "cancel" without any indication of further avaliable action.
-  I need to know that I can scroll down the bottom part of the datepicker, sliding "pick" behind the calender and revealing a "delete" button

**Comment by tarnung** [comment]
I don't plan on any more direct additions to this PR. It seems like a nice package as is.

The only thing I found is that there now only is a #search in the url when either search or task list are opened.

**Comment by munen** [comment]
@tarnung Thank you for the update! :pray: 

I'm currently testing on iOS and on the Desktop. I've updated the last test in https://github.com/200ok-ch/organice/pull/748. The final issue before we can merge https://github.com/200ok-ch/organice/pull/748 is the iOS regression on editing descriptions for which I'm currently testing options.

Since there are many (great!) changes in the last PRs, would you consider doing a code walk-through with me? We could do a screen-sharing session, or I could offer office space in Glarus where we could also have a coffee or tea together. Of course, all of these are optional. The alternative is that I'll do my best to do a code review at my speed and time and merge when I've gotten through.

**Comment by tarnung** [comment]
If the changes in  #748, #747 and in here are all to be merged, it might be easiest to only merge 751 since all code is already in here. If you prefer to go one by one and you can perform the necessary rebasing magic, that's fine with me too.

We can plan a remote code walkthrough. Just tell me when you have time to spare. I'm in no hurry since I can already use the changes on staging anyway :)

**Comment by munen** [comment]
> If the changes in #748, #747, and in here are all to be merged, it might be easiest only to merge 751 since all code is already in here.

Ack. I see no blockers to look straight at #751 for merging. I'm only looking at #748, because it is slightly smaller and introduced the iOS description scrolling issue.

> We can plan a remote code walkthrough. Just tell me when you have time to spare. I'm in no hurry since I can already use the changes on staging anyway :)

Sweet! This week is completely booked (work, templestay, meditation retreat). But next week, I'm pretty flexible from Monday to Sunday except for Monday afternoon/evening. If you have any preferences, the chances are high that we can do it, then. If you have no preferences, then I suggest Tuesday the 23rd at 10 am.

**Comment by tarnung** [comment]
Would Monday 22nd 10am work for you? That or Friday would be my best options for a spot during the day. Otherwise we'd have to make it an evening.

**Comment by munen** [comment]
> Would Monday 22nd 10am work for you? That or Friday would be my best options for a spot during the day. Otherwise we'd have to make it an evening.

That works well! I'll send you a Zoom invite via your hey email address.

**Comment by munen** [comment]
I have cherry-picked the two commits from me from PR https://github.com/200ok-ch/organice/pull/748.

I'm currently deploying the updated #751 to Staging.

**Comment by munen** [comment]
Last (known) issue on this PR: Tests on #748 are green. On #751, there are ten failing tests.

**Comment by munen** [comment]
Screenshot showcasing the functionality of the last commit: 
image

**Comment by munen** [comment]
@schoettl FYI, with merging #751 from tarnung, the user can input multi-line notes. I've made these changes to the code from you:

- https://github.com/200ok-ch/organice/pull/751/commits/9afa06a83daef0f8c3a34c8535dc85992a067e25
- https://github.com/200ok-ch/organice/pull/751/commits/d203478e6b9975e5840255f5a6c03356ac7374ae

Here's a showcase of what it looks like now: https://github.com/200ok-ch/organice/pull/751#issuecomment-971404751

I hope you're ok with these changes. Since this PR is already huge and builds on several other huge PRs, I think these changes are good for you, too, I have not opened a separate PR.

**Comment by munen** [comment]
I have updated Staging with the current state of #751.

**Comment by tarnung** [comment]
Seems good to me. At least from a user perspective. I can't speak to the effects of mulit line notes on the parser etc.
But since note parsing is broken anyway (as seen in #750) it's at least not worse ;)

**Comment by munen** [comment]
Using a capture template looks like this on iOS:

99F46EE2-1DB3-4355-B100-5D5DA6ACB02D

I’ll look into it on Monday. I only just realized it.

**Pull request merged**
