### PR TITLE
Logbook clocking

### PR DESCRIPTION
**Pull request by jamesnvc**
Addresses #99 by adding a "Clock In/Out" action to header entries.

 - [x] allow editing timestamps in logbook
 - [x] show duration overlay next to completed items
 - [x] intelligently show "clock in" or "clock out"

### CODE REVIEW

**Comment by munen** [comment]
Hi @jamesnvc 

This is great work! :confetti_ball: 

I've had a first read through the code and it looks good so far(; I also quickly tested against a file of mine and apart from the missing calculated times, it worked fine. 

I think you're still going, so I'm not going to interfere with finishing the calculation of times.

When you're done with the feature itself, it would be nice to have a unit test for the parser like [these](https://github.com/200ok-ch/organice/blob/master/src/components/OrgFile/OrgFile.unit.test.js#L20-L117) and an integration test like [this one](https://github.com/200ok-ch/organice/blob/master/src/components/OrgFile/OrgFile.integration.test.js#L68). If you didn't plan on doing them, I'd be happy to help out here.

Please give me a ping when you're done on the feature and I'll go through the code one more time and test it against some more files.

I'm stoked you're working on this and am very much looking forward to merging the PR and using the feature! 

Thank you very much :pray:

**Comment by jamesnvc** [comment]
Thanks @munen! I've added some tests & they all seem to be passing now. Please let me know if there's anything else I should change/add.

**Comment by munen** [comment]
@jamesnvc This is exceptional work! I read through the code again and tested against huge real life Org files. Both your code as well as your tests are rock solid.

> Please let me know if there's anything else I should change/add.

This PR is nothing but impeccable, there's nothing for this feature left to do(;

I'll happily merge your changes in - meaning the feature will be available on organice.200ok.ch within a few minutes.

Thank you for your amazing work - you'll make quite a few people very happy :pray: :bowing_man:

**Comment by munen** [comment]
I updated the changelog and added attribution: https://github.com/200ok-ch/organice/commit/656cadd73b0e9666ba8400a9c8a0fbc63724daaf

Thank you, again. This is a major step forward^^

**Comment by jamesnvc** [comment]
Thank you for the kind words and for organice! Absolutely my pleasure :)

**Pull request merged**
