### PR TITLE
Feat/additional themes

### PR DESCRIPTION
**Pull request by tarnung**
#539

### CODE REVIEW

**Comment by tarnung** [comment]
code light and smyck light are not usable right now. I have to tune highlighting and maybe some colors

**Comment by tarnung** [comment]
now we're good.

**Comment by munen** [comment]
An initial visual check of the themes shows that they all look amazing! :100: 

There is a little bug if there's no theme selected, yet:

The danger of checking against `undefined` continues(;

image

image

Of course, we can fix the issue inline in this PR. But my hunch in https://github.com/200ok-ch/organice/pull/534#issuecomment-717863785 that the lack of a default `colorScheme` will cause more problems later on is confirmed. So, it would be best if both (default and a more robust check) can be tackled.

**Comment by munen** [comment]
I looked into it a bit more. It was a good hunch at https://github.com/200ok-ch/organice/pull/534#issuecomment-717863785, indeed. `loadTheme` is called with the actual arguments `"null"` (as a string), because there's no default.

**Comment by tarnung** [comment]
I thought I had covered all the bases by checking against undefined AND "undefined" (as a string).
But actually having a default value would be better, I agree. I'll look into it later this week.

Something else that just came to mind:
I left the colors.css file intact to give the variables an initial value. This would be no longer necessary technically, since we set all the variables in code (once this reliably works). But I guess there's no harm in keeping it (apart from the duplication).

**Comment by tarnung** [comment]
I rebased, removed the check for 'undefined' and added a default value for theme.

**Comment by munen** [comment]
@tarnung Really good work! I've added contribution to the changelog and added a section to the documentation, because this is too pretty to leave it off the docs(;

image

**Pull request merged**
