### PR TITLE
[WIP] Feature: delete timestamps in the timestamp edit modal

### LINKED ISSUE #30: Ability to delete schedules and deadlines
- `organice` features SCHEDULED and DEADLINE timestamps and can manage them quite well.
- However, deletion of such a timestamp would have to be done by editing the description of the headline.
- Add a simple 'delete' button in the timestamp edit modal.

### PR DESCRIPTION
**Pull request by schoettl**
This should close #30 

@munen can you have a look at the TODO comments in my commit? I'm curious how to get this working :)

### CODE REVIEW

**Comment by munen** [comment]
@schoettl Thanks for taking a crack at this!

I'm sorry to say, but I did actually implement this during a [Hackathon](https://200ok.ch/posts/hack4glarus_hackathon_2019_winter_edition.html) we organized three weks ago. The PR is here: https://github.com/200ok-ch/organice/pull/125

It's my fault - there were duplicate issues and I closed only the more recent one (#83), but forget about about #30.

If it helps at all, it was quite hard to do - mostly the testing. Native timestamps aren't amazing - also in features. That's why in the long run, I'd like to replace them with a more feature rich date picker (for example one where you can see which day of the week you're selecting). There's a feature ticket for it here https://github.com/200ok-ch/organice/issues/36 

Voting to close this PR and issue #30

**Comment by munen** [comment]
Having said this, it's obviously not good UX wise that you didn't see that it's possible to delete timestamps(;

That's another negative of the native date picker. Deleting a timestamp is possible by clicking the 'x' inside the date picker: 
image

Interestingly pretty much the same as your initial UI(;

**Comment by schoettl** [comment]
Ah ok, I overlooked this tiny button :)

But in fact it is not displayed on my android phone... ah, it's not a button as in your screenshot but when I click on the picker, then there is a delete option in the dialog.

Can you merge only the first commit of this branch? It's refactoring, I don't know why there is the `<i>` tag in use, but it's deprecated in html5 in favor of `<em>` which does not make sense here either ^^

**Comment by munen** [comment]
Yeah, it’s tricky. On iOS you have to click the timestamp, then a menu comes up and there it has a “clear” action. 

06EF5955-4818-4FF1-8A06-C51B8B8E71FA

It’s pretty complicated, but the benefit of it being native is that it’s at least the same for every native app^^

**Comment by munen** [comment]
> Can you merge only the first commit of this branch? It's refactoring, I don't know why there is the <i> tag in use, but it's deprecated in html5 in favor of <em> which does not make sense here either ^^

I'll happily merge the first commit if an `<i>` tag is deprecated. I didn't know about that know. It doesn't mention it on [mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/i) and out of my head, I thought that other popular projects fontawesome use them and checked that. They also still do:

image

I assume you're referring [this the w3org article](https://www.w3.org/International/questions/qa-b-and-i-tags). The issue with w3org sometimes is that browser vendors and w3org don't always agree.

So, I'm not saying we can't use `span` in favor of `i` tags, but I want to understand the issue first(;

**Comment by schoettl** [comment]
Well, right, I concluded too quickly. I always read, that I'm supposed to use semantic tags (like `<em>`) and because `<i>` was traditionally italic font, it should not be used anymore to to make text italic.

> Use the `<i>` element only when there is not a more appropriate semantic element, such as: [1]

And `<span>` is a generic inline containers without the smell of italic. And I often saw icons to be included with spans. But I guess some big "icon providers" gave the `<i>` a new meaning (-> icon) :) I did not notice that. No need to merge the commit! We better stick to the icon provider standard.

[1] https://www.w3schools.com/tags/tag_i.asp

**Comment by munen** [comment]
I agree. It’s confusing stuff. The whole semantic web and federation battle seems to be lost in the big, but in the small I’m of course in favor we keep fighting for them^^

For an SPA like organice, the whole topic is tricky anyway. The semantics of the used tags in organice are not relevant for SEO, but they might at some point be for blind users. However, I doubt that organice could be used from a semantic browser for blind people atm. Emacs on the other hand would be a great option for that. Using organice with the build in accessibility features from iOS works quite ok, though. But that ignores all the markup and just speaks what it can see^^

**Pull request closed without merging**
