### PR TITLE
webdav: add initial sync backend

### PR DESCRIPTION
**Pull request by TristanCacqueray**
This change adds a new sync backend for the WebDAV protocol.

* TODO polish the signin form.
* TODO implement directory listing filter and getMore cursor.
* TODO better handle errors.

closes: #77

### CODE REVIEW

**Comment by munen** [comment]
Hi @TristanCacqueray 

The code in the PR looks really solid! Thank you for creating the one feature that quite a few people have been asking for in the last days 🙏

Before I merge it, I'd like to test it first hand and polish the login screen a little. I also like how you handled the other two missing functions. 

Unfortunately, due to no error of you, my first test didn't work, though. I tried to connect to the one OwnCloud instance that I have access to via WebDAV. It looks like they don't set the CORS headers as required to access it from JavaScript, though. I'll dig deeper and try to find a hoster with which I can test. If you can point me to a server that you used for testing, I'll happily use that one, of course.

**Comment by TristanCacqueray** [comment]
Hi @munen , thank you for the feedback :-)
To avoid CORS issue, I guess the easiest would be to document that the build should be served by the webdav host, and thus the login button could just be the path of the webdav location. Alternatively, here is a test (insecure) configuration I used with apache:

```
Alias /webdav /srv/webdav
<Location /webdav>
    Options Indexes
    DAV On
    # Uncomment for auth
    #AuthType Basic
    #AuthName "webdav"
    #AuthUserFile /etc/httpd/webdav.password
    #Require valid-user
    Header always set Access-Control-Allow-Origin "*"
    Header always set Access-Control-Allow-Methods "GET,POST,OPTIONS,DELETE,PUT,PROPFIND"
    Header always set Access-Control-Allow-Headers "Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,Authorization,X-CSRF-Token,Depth"
    Header always set Access-Control-Allow-Credentials true

    Require all granted
</Location>
```

**Comment by munen** [comment]
Great, thank you!

I opened a new PR in which I'll add changes while I'm testing: https://github.com/200ok-ch/organice/pull/84

The biggest change so far is: My logins always fail, so it would be convenient to fall back to the landing page(;

**Comment by TristanCacqueray** [comment]
New change adds directory listing sort, prevents delete exception when response is 404 (which happen the first time the user click on "Store settings in sync backend".
I would appreciate help to polish the login button as I don't know much how html and css works...

**Comment by munen** [comment]
I'll take care of the login screen, you're doing quite enough with the integration of WebDAV as a back-end^^

**Comment by munen** [comment]
NB: I see that you force pushed whilst keeping just one commit. I understand why you did that (to keep the history clean). However I also started to work on a branch based on your work and now my work is outdated(;

Can we use merges for the time being as long as both of our branches are public and we might both work on them, please?

I'll redo my branch by starting new from yours and then I'll cherry-pick my changes over.

**Comment by munen** [comment]
Having said that: Great additions in your latest push! I like your style of getting things done quickly^^

**Comment by munen** [comment]
@TristanCacqueray Ok, so I've set up a local webdav server using this Docker image: https://github.com/sashgorokhov/docker-nginx-webdav

I did patch the `/etc/nginx/conf.d/default.conf` file to include CORS headers:

```
add_header "Access-Control-Allow-Origin" * always;
add_header "Access-Control-Allow-Methods" "GET, HEAD, POST, PUT, OPTIONS, MOVE, DELETE, COPY, LOCK, UNLOCK, PROPFIND" always;
add_header "Access-Control-Allow-Headers" "Authorization, Origin, X-Requested-With, Content-Type, Accept, DNT, X-CustomHeader, Keep-Alive,User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Range, Range, Depth" always;
```

I can login to this server via HTTP and Basic Auth (because as I read that's how you are logging in).

But when logging in from organice, I'm getting this in the Nginx log:

```
2019/10/26 17:49:37 [error] 12#0: *14 no user/password was provided for basic authentication, client: 172.17.0.1, server: , request: "OPTIONS // HTTP/1.1", host: "localhost", referrer: "http://localhost:3000/files"
```

It's a little curious, because `login` and `password` are actually set in the call to `createClient`.

**Comment by munen** [comment]
Ok, so I did try to set up a local Apache2 to test it similarly to you. And I do get Apache and WebDAV to run with this config:

```
Alias /webdav /home/munen/tmp/dav/

<Location /webdav>
    Options Indexes
    DAV On
    AuthType Basic
    AuthName "webdav"
    AuthUserFile /home/munen/tmp/dav/.htpasswd
    Require valid-user

    Header always set Access-Control-Allow-Origin "*"
    Header always set Access-Control-Allow-Methods "GET,POST,OPTIONS,DELETE,PUT,PROPFIND"
    Header always set Access-Control-Allow-Headers "Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers,Authorization,X-CSRF-Token,Depth"
    Header always set Access-Control-Allow-Credentials true

    Require all granted
</location>

```

The `.htpasswd`, I did set up with `htpasswd -c .htpasswd webdav`.

I can log in `cadaver http://localhost/webdav/` and providing my credentials. So far so good.

However, logging in from organice doesn't work, because I'm missing the CORS headers. Your configuration from above is very much the same as when I search the internet for `apache2 webdav cors`. I tried from Firefox and Chromium. I also tried from `localhost` and `127.0.0.1`.

So far, no luck. Do you see what I'm missing here?

**Comment by munen** [comment]
Here's how I set up Apache2 locally: https://github.com/200ok-ch/organice/pull/85/commits/813eeb42f78226d0e2bce634347771c5d407c4e2

When we get this to work, it might be good usable information for the next person to try it(;

**Comment by munen** [comment]
In any case, when circumventing the CORS issue by building a static version of organice and putting it onto the same Apache2 instance, I am able to login!

**Comment by TristanCacqueray** [comment]
@munen, alright next time I'll add new commits to that PR. Thank you for taking over the feature!

About the CORS issue, it seems like the OPTIONS requests are getting denied because they are sent without the authorization header, thus I think that apache also need to have this top-level configuration:
```httpd
RewriteEngine On
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteRule ^(.*)$ $1 [R=200,L]
```

**Comment by munen** [comment]
Sweet baby Jesus, it works! You know your Apache and WebDAV, Sir^^

I'll just do a little bit more cleanup and then I'll merge.

NB: I'm honestly impressed about this PR. You probably know, but you did an amazing job, here!

**Comment by TristanCacqueray** [comment]
Thank you the other provider was very easy to adapt :) Though it's the first time I use this webdav client and the implementation can probably be improved (e.g. use stream download).

In any case, authentication failure results in the initial stat request to return 401 or 403. Here is a slightly better error handling but that should probably be tested first after the user sign-in: d6c1f990cc0009af221461392e784ebed29e2b38

**Comment by munen** [comment]
There's always room for improvement^^ However, some people complained about organice not having WebDAV and didn't get back to me when I explained where to start working on it. From you, I first heard with an awesome PR. That's a very rare condition on the Internet. You made my day!

I did also finish my work for the time being. This is what it looks and behaves like now: 

demo

I also did some refactoring of the WebDAV component, but it's all minor stuff compared to what you did! If you're interested, my changes are all in this PR: https://github.com/200ok-ch/organice/pull/85

**Comment by munen** [comment]
I just added your new feature with attribution to the [changelog](https://github.com/200ok-ch/organice/commit/147ee9df3e2c774f59a56e8d2dccbe32a367e621) - and I had quite a few places to chage in the documentation(; 

Thank you, again! You've made a few people happy today^^ 🙏🙇

**Comment by TristanCacqueray** [comment]
Awesome, thank you for publishing organice =)

**Comment by sje30** [comment]
I get an error when trying to use webdav on our nextcloud server:

    There was an error retrieving files!

any clues?

**Comment by munen** [comment]
@sje30 Yes, I update the readme with a potential reason - including two new screencasts and boilerplate webdav configuration: https://github.com/200ok-ch/organice/#webdav

**Comment by sje30** [comment]
Thanks.  I'm getting a slightly different erorr:

```
/files:1 Access to XMLHttpRequest at 'https://[ELIDED]' from origin 'https://organice.200ok.ch' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```

Is that a problem on my end?

**Comment by munen** [comment]
@sje30 Thank you for sharing the error message. It's very clear, your back-end doesn't have the necessary CORS headers set. Without them, it will not be possible for you to log in from _any_ web-service through a web-browser that's not running on the exact same domain and port like your back-end. Whoever administers your synchronization back-end will have to take care of that. It's technically impossible to access it from JavaScript and a browser otherwise.

I have put example config for Apache in the [README](https://github.com/200ok-ch/organice/#setup-your-own-webdav-server). You might not be running Apache as a back-end, but the which need to be set are the same.

**Comment by sje30** [comment]
Thank you.  I will talk to the local experts then armed with this knowledge!

**Comment by munen** [comment]
@sje30 Good luck! And hope to see you using organice, soon(;

**Comment by sje30** [comment]
thanks.  in the meantime, do you know of any other webdav servers that are publicly available and work with organice?

**Comment by munen** [comment]
There's installation instructions for a self hosted Apache in the Readme. Having said that, I'm a happy Dropbox User. Google Drive also works fine. The latter two options are not FOSS, but have the benefit that they habe a nice JavaScript SDK and organice just works out of the box.

**Pull request merged**
