### PR TITLE
Added deadline display option on headlines

### PR DESCRIPTION
**Pull request by dmorlitz**
This PR adds the option to display DEADLINE values as an addition (near the clocking value) on each headline.  There is a settings panel option that allows you to turn this feature on and off.  The setting is persisted in the .organice-config.json file.

The default for this option is false - so there is no change to the default behavior of Organice - until you enable this option via Settings.

### CODE REVIEW

**Comment by dmorlitz** [comment]
Could you please tell me how to rebase this pull request to ensure that my changes are compatible with the latest version of Organice?

**Comment by schoettl** [comment]
You can use git in the terminal. See `git rebase --help` or [here](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) for details. If you get a conflict during rebase you can `git rebase --abort` or `git rebase --continue` (after resolving conflicts and adding the files).

**Comment by dmorlitz** [comment]
This pull request has been re-based to the current Organice master - and is ready for review

**Comment by munen** [comment]
@dmorlitz This can be a really useful change for some workflows! It's an addition I wouldn't have thought of since Emacs doesn't have this functionality. I would have used the 'search' feature to get a custom view with only the deadlines - similar to Emacs. Having said so, I think it adds good value to show deadlines inline with the 'regular' tasks in a project! :100: It also works well, because we don't show a lot of stuff right-aligned - only the clock display. Emacs shows tags right aligned.

I have tested this feature on FF/Linux and Safari/iOS. I found a small bug that I fixed (when both 'clock display' and 'deadline display' are enabled, their values are a little close together. I fixed this.

I found one more design regression - in responsive mode and on iOS, the dates don't always align nicely or aren't even completely shown (because they get cut off). This is not a blocker for an optional feature, though. I'll add a separate issue for it. I wanted to mention it here for completeness of the review.

I have updated the changelog and documented the option in sample.org.

Thank you for the great feature and thank you doubly for doing the extra chore of rebasing it to current `master`, making the review process really smooth, even though it took me a long time to get to it. It's much appreciated, thank you :pray: :bow:

**Comment by munen** [comment]
Side note: I'm unable to make changes to this PR or your master branch directly because your master branch is write protected, even when a PR is opened from it. So, I made the changes locally and pushed them directly to master. All the changes are now included, so I'll go ahead and close this PR. In other PRs, like https://github.com/200ok-ch/organice/pull/890, you have created a new branch on your fork (e.g. dmorlitz:table-editor-icon-fix) from which you opened the PR. In these cases, I can make changes and push them without it appearing as if I simply closed the PR.

**Comment by dmorlitz** [comment]
I am happy that I am able to contribute valuable additions to this wonderful project.  Thank you for the review and the comments.  I will take a look and see if I can figure out a good fix for the responsive mode issue.  I will also try and use Github better, so the PRs are easier for you to review.

Thank you again for a wonderful project.  It has really improved my daily productivity.

**Comment by munen** [comment]
No worries about the GH PR process. I primarily wanted to mention it so that it doesn't look like I just closed your PR(;

Thank you for your kind words :pray: Users and contributors like you make the extra effort worthwhile - apart from me being a happy daily user, myself, of course :joy:

**Pull request closed without merging**
