### PR TITLE
Fixed rotation of table editor icons to reflect their action

### PR DESCRIPTION
**Pull request by dmorlitz**
This pull request rotates the icons in the table editor modal to properly reflect the rows and columns that each button affects.

### CODE REVIEW

**Comment by dmorlitz** [comment]
I appear to be "branch ignorant" and managed to get 2 different features (which I thought I made branches for) - all pushed into my master.  Can you please give me some tips to get these "untangled"?

**Comment by schoettl** [comment]
You can `git cherry-pick` the commits that are not related to this PR into a new branch and then create a new PR for that branch.

In this branch, you then can `git reset --hard` (use with care) and `git push --force` to remove the unrelated commits from this PR.

**Comment by dmorlitz** [comment]
Thank you for the tips.  Since these changes are simple - and I already have them as separate branches on my test system - I think it might be best for me to just close this PR and re-do it from the proper github branches, rather than from my master branch.

**Comment by dmorlitz** [comment]
Since the PRs were in separate files, I just ended up using git revert to
remove the update from the 2nd PR that was really part of the 1st.

Thank you again for pointing me in the right direction.

**Pull request closed without merging**
