### PR TITLE
Parse inline markup non-greedily

### PR DESCRIPTION
**Pull request by lechten**
Fixes issue #198, passes new tests in PR #157.

### CODE REVIEW

**Comment by munen** [comment]
Hi @lechten 

Thank you very much for tackling this long standing issue :pray: 

I agree that your fix passes the test from PR #157 which I added to your branch. So kudos on that :muscle: 

Having said so, I'm afraid that the test we created in advance doesn't hold up to the real world requirement. Here's a screenshot showing current master (worst option), your branch (improvement, but still room too improve) and Emacs (correct):

image

Are you interested in tackling this issue and see it through to the end?

Many greetings from the reClojure conference which will switch to EmacsConf in 4 hours :joy:

**Comment by munen** [comment]
What I have right now: https://github.com/200ok-ch/organice/tree/fix/towards-fixing-issue-198

**Comment by lechten** [comment]
Have fun at the conferences, @munen :smile: 

Now, a boundary in the form of start of string, whitespace, parenthesis, apostroph, or quote needs to be present.

Previously, `[^\s,'](.*)[^\s,']` required two characters. Now only a single character is required. In case of multiple characters, the final one can now be a whitespace, comma, or apostroph. Note sure whether this is OK...

**Comment by munen** [comment]
> Have fun at the conferences, @munen :smile: 

Thanks, I'm having a lot of fun - great people and great talks. Most importantly, though, you've just solved the big riddle of the complicated Regexp! :100: :rocket: 

I have updated the changelog and added attribution to you.

Thank you for the amazing work - the diff is tiny, but you're the forth or fifth person to tackle this bug, and you're the one who made it. Big :+1:, thank you for this very important contribution :pray: :bow:

**Comment by lechten** [comment]
Thank you for the incredibly quick feedback and handling of this issue!

**Comment by munen** [comment]
> Thank you for the incredibly quick feedback and handling of this issue!

Any time😂

**Pull request merged**
