### PR TITLE
Add note on 200ok's instance

### PR DESCRIPTION
**Pull request by branch14**

### CODE REVIEW

**Comment by branch14** [comment]
What's going on? I think some rebasing happened while I was taking a breath.

**Comment by branch14** [comment]
I just wanted to complete https://github.com/200ok-ch/organice/issues/29, which it a somewhat unrelated TODO in the description. :)

**Comment by munen** [comment]
> What's going on? I think some rebasing happened while I was taking a breath.

That happened: https://circleci.com/gh/200ok-ch/organice/97

Therefore I removed a commit from `master`.

I'll clean up your branch before merging. And I won't rebase `master` now anymore when there's more than one contributor(; 

But before merging, GDrive has to work.

**Comment by munen** [comment]
> I just wanted to complete #29, which it a somewhat unrelated TODO in the description. :)

It's highly related. I didn't advertise the public instance as long as only half the login methods work. The only other option would have been to rewrite the README and remove the GDrive from Login. But then, in all honesty, I probably would never have worked on setting up GDrive.

**Comment by munen** [comment]
@branch14 I rebased your branch to remove the obsolete commit. Please reset your HEAD and pull, again.

**Pull request merged**
